[default.general]
chip = "nrf52833_xxAA" # uncomment this line for micro:bit V2
# chip = "nrf51822_xxAA" # uncomment this line for micro:bit V1

#[default.probe]
# The speed in kHz of the data link to the target.
#speed = 500

[default.reset]
halt_afterwards = false

[default.rtt]
enabled = false

[default.gdb]
enabled = true
